/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AccountProfile: typeof import('./src/components/Account/AccountProfile.vue')['default']
    Achievement: typeof import('./src/components/Activity/List/Achievement.vue')['default']
    ACol: typeof import('ant-design-vue/es')['Col']
    AddSocialMedia: typeof import('./src/components/Profile/UserGuide/AddSocialMedia.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    Alert: typeof import('./src/components/Alert/Alert.vue')['default']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Badge: typeof import('./src/components/Activity/Detail/Badge.vue')['default']
    Campaign: typeof import('./src/components/Activity/List/Campaign.vue')['default']
    CampaignsDetail: typeof import('./src/components/Activity/Detail/CampaignsDetail.vue')['default']
    Condition: typeof import('./src/components/Condition/Condition.vue')['default']
    CropperModal: typeof import('./src/components/Account/CropperModal.vue')['default']
    DialogBilibiliBind: typeof import('./src/components/Condition/DialogBilibiliBind.vue')['default']
    DialogBilibiliTag: typeof import('./src/components/Condition/DialogBilibiliTag.vue')['default']
    DialogCodeList: typeof import('./src/components/Condition/DialogCodeList.vue')['default']
    DialogCodeVerify: typeof import('./src/components/Condition/DialogCodeVerify.vue')['default']
    DialogWeiboBind: typeof import('./src/components/Condition/DialogWeiboBind.vue')['default']
    DialogWeiboTag: typeof import('./src/components/Condition/DialogWeiboTag.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    IconFont: typeof import('./src/components/Activity/Detail/IconFont.vue')['default']
    Item: typeof import('./src/components/Activity/List/Item.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Nav: typeof import('./src/components/Nav/Nav.vue')['default']
    PanelBilibiliTag: typeof import('./src/components/Condition/PanelBilibiliTag.vue')['default']
    PanelCode: typeof import('./src/components/Condition/PanelCode.vue')['default']
    PanelWeiboTag: typeof import('./src/components/Condition/PanelWeiboTag.vue')['default']
    Participants: typeof import('./src/components/Activity/Detail/Participants.vue')['default']
    ProfileCampaign: typeof import('./src/components/Activity/List/ProfileCampaign.vue')['default']
    ProfileItem: typeof import('./src/components/Activity/List/ProfileItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectIdentity: typeof import('./src/components/Profile/UserGuide/SelectIdentity.vue')['default']
    SelectTheme: typeof import('./src/components/Profile/UserGuide/SelectTheme.vue')['default']
    SetDomain: typeof import('./src/components/Profile/UserGuide/SetDomain.vue')['default']
    Toast: typeof import('./src/components/Alert/Toast.vue')['default']
  }
}
